# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "azurerm" {
    container_name       = "ghaf-infra-ssd-tfstate-container"
    key                  = "prod-eun/rg.tfstate"
    resource_group_name  = "ghaf-infra-ssd-0-state-eun"
    storage_account_name = "ghafinfrassd0stateeun"
  }
}
